### ISSUE TITLE
表示不会搞

### ISSUE THREAD

**Issue by SaucePlum** [NWYLZW/qq-guild-sdk#1]
![image](https://user-images.githubusercontent.com/48905684/155014120-68e2c95f-3d58-430c-8131-75ece41be5bb.png)

**Comment by NWYLZW** [comment]
在你的 package.json 指定 type: "module"
或者将你的文件后缀修改为 .mjs
或者使用 commonjs 的 require api，`require('qq-guild-sdk').createBot|Bot`

**Comment by SaucePlum** [comment]
能写一份cil已构建好可以运行的文件给我嘛

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月22日(周二) 下午2:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [NWYLZW/qq-guild-sdk] 表示不会搞 (Issue #1)




 
在你的 package.json 指定 type: "module"
 或者将你的文件后缀修改为 .mjs
 或者使用 commonjs 的 require api，require('qq-guild-sdk').createBot|Bot
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NWYLZW** [comment]
> 能写一份cil已构建好可以运行的文件给我嘛
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年2月22日(周二) 下午2:08 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [NWYLZW/qq-guild-sdk] 表示不会搞 (Issue #1) 在你的 package.json 指定 type: "module" 或者将你的文件后缀修改为 .mjs 或者使用 commonjs 的 require api，require('qq-guild-sdk').createBot|Bot — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

就照着上面改一下就行啦，不麻烦的

**Comment by SaucePlum** [comment]
改了还是不行呀



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月23日(周三) 上午9:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [NWYLZW/qq-guild-sdk] 表示不会搞 (Issue #1)




  
能写一份cil已构建好可以运行的文件给我嘛
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年2月22日(周二) 下午2:08 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [NWYLZW/qq-guild-sdk] 表示不会搞 (Issue #1) 在你的 package.json 指定 type: "module" 或者将你的文件后缀修改为 .mjs 或者使用 commonjs 的 require api，require('qq-guild-sdk').createBot|Bot — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
就照着上面改一下就行啦，不麻烦的
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NWYLZW** [comment]
<img width="291" alt="image" src="https://user-images.githubusercontent.com/51358815/155251922-7cfb3c81-5b00-439e-b309-e4dc529f668f.png">

看起来是 nodejs 对 modulejs 的解构不支持，你试着把 index.js 上方的改成这个格式
具体原因我还得研究一下

**Comment by NWYLZW** [comment]
我刚刚试了这样写是能够运行了

**Comment by SaucePlum** [comment]
跑起来了，是否沙箱模式在哪设置啊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月23日(周三) 上午10:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [NWYLZW/qq-guild-sdk] 表示不会搞 (Issue #1)




 
我刚刚试了这样写是能够运行了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NWYLZW** [comment]
https://nwylzw.github.io/qq-guild-sdk/api/core/Bot.html#bot-options
可查阅文档，默认开启（（（（大概
